## Chaining promises

The then method itself returns a promise:
```
var promise = readFile()
var promise2 = promise.then(readAnotherFile, console.error)
```
This promise represents the return value for either of its onFulfilled or onRejected handlers if specified. Since only one resolution is possible, the promise proxies whichever handler is called.

Since then returns a promise, it means promises can be chained to avoid callback hell.
```
readFile()
  .then(readAnotherFile)
  .then(doSomethingElse)
  .then(...)
```
- Promises model synchronous functions. One such way is using return for continuation instead of calling another function.
```
readFile()
  .then(function (buf) {
    return JSON.parse(buf.toString())
  })
  .then(function (data) {
    // do something with `data`
  })
```

#### Error handling in promises
In addition to return, you also can use the throw keyword and try/catch semantics. This may be one of the most powerful features of promises. For example, consider the following synchronous code:
```
try {
  doThis()
  doThat()
} catch (err) {
  console.log(err)
}
```
Similarly for asynchronous:
```
doThisAsync()
  .then(function (data) {
    if (!data.element) throw new Error('Expected element to be there')
  })
  .catch(err){
    console.log(err)
  }
```
